title: Pagination in API Documentation
description:  The repository contains the final project for Vistula post-graduate studies on Technical Communication. At the same time the repository aims to provide a comprehensive understanding of pagination within the context of API documentation.
theme: just-the-docs

url: https://guinea-pigg.github.io/Pagination_in_API_Documentation

# Logo
logo: "/img/logo.png"

#Favicon
favicon_ico: "/img/logo.png"

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024 Magdalena Maffioli. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "See this page on GitHub"
gh_edit_repository: "https://github.com/guinea-pigg/Pagination_in_API_Documentation.git" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

color_scheme: my_style

