title: Pagination in API Documentation
description:  The repository contains the final project for Vistula post-graduate studies on Technical Communication. At the same time the repository aims to provide a comprehensive understanding of pagination within the context of API documentation.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
